[build]
  publish = "dist/gamer-id-browser"
  command = "npm run build"
[dev]
  publish = "dist/gamer-id-browser"
  command = "ng serve"
[functions]
  directory = "lambda"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200